version: '3'
services:
  openam:
    build:
      context: .
      args:
        - AM_REMOTE_FILENAME=${AM_REMOTE_FILENAME}
      dockerfile: Dockerfile
    environment:
      - AM_HOSTNAME=${AM_HOSTNAME}
      - AM_LOCAL_PORT=${AM_LOCAL_PORT}
      - AM_REMOTE_PORT=${AM_REMOTE_PORT}
      - AM_REMOTE_FILENAME=${AM_REMOTE_FILENAME}
      - AM_ADMIN_PASSWORD=${AM_ADMIN_PASSWORD}
      - AM_SESSION_COOKIE_NAME=${AM_SESSION_COOKIE_NAME}
    ports:
      - "${AM_LOCAL_PORT}:${AM_REMOTE_PORT}"
    extra_hosts:
      - "${AM_HOSTNAME}:127.0.0.1"
